# Generated by Django 2.1.1 on 2018-09-20 06:22

import apka.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=60)),
                ('code', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(default=apka.models.increment_id, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=40)),
                ('date', models.DateField(default=datetime.datetime(2018, 9, 20, 6, 22, 40, 642974, tzinfo=utc))),
                ('hours', models.FloatField(default=8)),
                ('hour_begin', models.TimeField(default=datetime.time(7, 45))),
                ('hour_end', models.TimeField(default=datetime.time(16, 0))),
                ('break_time', models.TimeField(default=datetime.timedelta(0, 1800))),
                ('test', models.BooleanField(default=True)),
                ('action', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('L', 'L'), ('I', 'I'), ('Z', 'Z'), (' ', ' ')], default=' ', max_length=13)),
                ('project_id', models.ForeignKey(db_column='project_id', on_delete=django.db.models.deletion.CASCADE, to='apka.Project')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
    ]
