# Generated by Django 2.1.1 on 2018-09-21 06:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0003_auto_20180921_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='advancement',
            field=models.IntegerField(choices=[(0, '0'), (25, '25'), (50, '50'), (75, '75'), (100, '100')], default='0'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 21, 6, 0, 35, 503754, tzinfo=utc)),
        ),
    ]
