# Generated by Django 2.1.1 on 2018-09-25 07:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0006_auto_20180925_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 7, 30, 54, 545531, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
