# Generated by Django 2.1.1 on 2018-09-25 08:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0008_auto_20180925_0942'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 25, 8, 14, 13, 754197, tzinfo=utc)),
        ),
    ]
