# Generated by Django 2.1.1 on 2018-09-28 13:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apka', '0010_auto_20180928_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 28, 13, 29, 21, 276836, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
    ]
